import uuid
from datetime import datetime

from sqlalchemy import Column, String, DateTime, ForeignKey, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.database import Base


class MealPlan(Base):
    """
    A meal plan for a mother, generated by the Nutritionist Agent from her
    reports + continuous monitoring trends, or authored directly by a doctor.
    A PHM or doctor reviews an agent-suggested plan and confirms or edits it
    before it reaches the mother.
    """
    __tablename__ = "meal_plans"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    mother_id = Column(UUID(as_uuid=True), ForeignKey("mothers.id"), nullable=False)
    source_report_id = Column(UUID(as_uuid=True), ForeignKey("reports.id"))  # nullable: may be trend-only

    trimester = Column(String)  # "1" | "2" | "3"
    plan_sinhala_msg = Column(Text, nullable=False)
    warning_sinhala_msg = Column(Text)  # e.g. tea/coffee near iron, high sodium if BP trending up

    origin = Column(String, default="agent")  # "agent" | "doctor_authored"
    status = Column(String, default="pending_review")  # "pending_review" | "confirmed" | "edited"
    reviewed_by_role = Column(String)   # "phm" | "doctor"
    reviewed_by_id = Column(UUID(as_uuid=True))

    created_at = Column(DateTime, default=datetime.utcnow)

    mother = relationship("Mother", back_populates="meal_plans")
    source_report = relationship("Report", back_populates="meal_plans")